import { Employee, EmployeeProfile, CategoryOptions } from '../types';

export const mockEmployees: Employee[] = [
    {
        id: 1,
        employee_id: 101,
        name: 'John Doe',
        birthday: '1990-05-15',
        annual_leave_balance: 12,
        sick_leave_balance: 8,
        status: 'ACTIVE',
    },
    {
        id: 2,
        employee_id: 102,
        name: 'Jane Smith',
        birthday: '1988-11-20',
        annual_leave_balance: 10,
        sick_leave_balance: 5,
        status: 'ACTIVE',
    },
    {
        id: 3,
        employee_id: 103,
        name: 'Robert Brown',
        birthday: '1995-02-10',
        annual_leave_balance: 15,
        sick_leave_balance: 10,
        status: 'INACTIVE',
    },
    {
        id: 4,
        employee_id: 104,
        name: 'Emily Davis',
        birthday: '1992-07-25',
        annual_leave_balance: 8,
        sick_leave_balance: 3,
        status: 'ACTIVE',
    },
    {
        id: 5,
        employee_id: 105,
        name: 'Michael Wilson',
        birthday: '1985-12-05',
        annual_leave_balance: 20,
        sick_leave_balance: 12,
        status: 'ACTIVE',
    },
];

export const mockCategoryOptions: CategoryOptions = {
    divisions: [
        { id: '1', title: 'Engineering' },
        { id: '2', title: 'HR' },
        { id: '3', title: 'Sales' }
    ],
    departments: [
        { id: '1', title: 'Software' },
        { id: '2', title: 'Recruitment' },
        { id: '3', title: 'Marketing' }
    ],
    subDepartments: [
        { id: '1', title: 'Frontend' },
        { id: '2', title: 'Backend' }
    ],
    units: [
        { id: '1', title: 'Unit A' },
        { id: '2', title: 'Unit B' }
    ],
    lines: [
        { id: 101, name: 'John Doe' },
        { id: 105, name: 'Michael Wilson' }
    ]
};

export const mockEmployeeProfiles: EmployeeProfile[] = [
    {
        id: 1,
        employee_id: 171,
        name: 'Rakibul Hassan Rakib',
        birthday: '2000-05-11',
        annual_leave_balance: 15,
        sick_leave_balance: 10,
        status: 'ACTIVE',
        division_id: '1',
        department_id: '1',
        sub_department_id: '1',
        unit_id: '1',
        line_manager_id: null,
        email: 'admin@peopleflow.com',
        phone: '01968627606',
        designation: 'Jr. Software Engineer',
        joining_date: '2023-01-01',
        confirmed: 1,
        confirmation_date: '2023-07-01',
        role: 'superadmin',
        gender: 'MALE',
        religion: 'islam',
        blood_group: 'O+',
        fathers_name: 'Mr. Hassan',
        mothers_name: 'Mrs. Hassan',
        relationship_status: 'single',
        present_address: 'Road: 9 House: 485, Mirpur-10, Dhaka',
        permanent_address: 'Dhaka, Bangladesh',
        skype: 'live:rakib',
        official_gmail: 'rakibul@peopleflow.com',
        github: 'rakib-hassan',
        nid: '123456789012',
        tin: '987654321098',
        breakfast: 1,
        lunch: 1,
        beef: 0,
        fish: 1,
        official_mac: '40:1C:83:83:40:C8',
        personal_mac: 'A0:51:0B:41:A6:31'
    },
    {
        id: 101,
        employee_id: 101,
        name: 'John Doe',
        birthday: '1990-05-15',
        annual_leave_balance: 12,
        sick_leave_balance: 8,
        status: 'ACTIVE',
        division_id: '1',
        department_id: '1',
        sub_department_id: '1',
        unit_id: '1',
        line_manager_id: '102',
        email: 'user@peopleflow.com',
        phone: '1234567890',
        designation: 'Senior Developer',
        joining_date: '2020-01-01',
        confirmed: 1,
        confirmation_date: '2020-07-01',
        role: 'user',
        gender: 'MALE',
        religion: 'christianity',
        blood_group: 'O+',
        fathers_name: 'Mr. Doe',
        mothers_name: 'Mrs. Doe',
        relationship_status: 'married',
        present_address: '123 Main St',
        permanent_address: '456 Old Town',
        skype: 'john.doe',
        official_gmail: 'john.doe@work.com',
        github: 'johndoe',
        nid: '123456789',
        tin: '987654321',
        breakfast: 1,
        lunch: 1,
        beef: 0,
        fish: 1,
        official_mac: 'A0:51:0B:41:A6:31',
        personal_mac: '48:01:C5:AA:10:A7'
    },
    {
        id: 102,
        employee_id: 102,
        name: 'Michael Scott',
        birthday: '1980-03-15',
        annual_leave_balance: 14,
        sick_leave_balance: 6,
        status: 'ACTIVE',
        division_id: '3',
        department_id: '3',
        sub_department_id: null,
        unit_id: null,
        line_manager_id: '1',
        email: 'manager@peopleflow.com',
        phone: '0987654321',
        designation: 'Regional Manager',
        joining_date: '2015-06-01',
        confirmed: 1,
        confirmation_date: '2015-12-01',
        role: 'teamlead',
        gender: 'MALE',
        religion: 'christianity',
        blood_group: 'B+',
        breakfast: 1,
        lunch: 1,
        beef: 1,
        fish: 0
    },
    {
        id: 103,
        employee_id: 103,
        name: 'Toby Flenderson',
        birthday: '1985-02-22',
        annual_leave_balance: 10,
        sick_leave_balance: 5,
        status: 'ACTIVE',
        division_id: '2',
        department_id: '2',
        sub_department_id: null,
        unit_id: null,
        line_manager_id: '1',
        email: 'hr@peopleflow.com',
        phone: '01711223344',
        designation: 'HR Representative',
        joining_date: '2018-09-10',
        confirmed: 1,
        confirmation_date: '2019-03-10',
        role: 'hr',
        gender: 'MALE',
        religion: 'other',
        blood_group: 'AB-',
        breakfast: 0,
        lunch: 1,
        beef: 0,
        fish: 1
    }
];
